:sparkles: Feat: Recipe CRUD 구현
one-day-one-meal/one-hour-one-meal pull request #46
Opened 2024-06-12 11:08 UTC by 1hyung

## 요약
> 간단 요약

Recipe CRUD 구현했습니다.

## 작업 사항

> PR에서 작업한 사항들을 적어주세요(이미지, 스크린샷등을 활용해도 좋아요)

## 리뷰 요청 사항(선택)

> 리뷰시 봐주었으면 하는 부분이 있다면 적어주세요

CRUD 구현한 Service 파일과 RecipeRepository 생성자 부분 확인 부탁드립니다.
RecipeRepository 파일에서 생성자 Ctrl + 클릭했을 때 이동이 안되는데 괜찮은지 모르겠습니다.
---
### 해결한 이슈
closes: #16

2024-06-12 14:50 UTC, devitssu requested changes

2024-06-12 14:50 UTC, devitssu commented on src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/repository/v1/RecipeRepository.kt
> +    fun findByCourseAndId(course: Course, id: Long): Optional<Recipe>
반환타입을 `Recipe?`로 바꾸는게 좋을거같아요!
Optional은 자바에서 null을 다루기위해 사용하는건데 코틀린은 nullable 타입을 구분할 수 있으니 굳이 사용할 필요가 없어요

2024-06-12 14:50 UTC, devitssu commented on src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/service/v1/RecipeService.kt
> +            .orElseThrow { RuntimeException("Course not found") }
자바의 향이 많이 느껴지는 코드네요🧐
익숙합니다ㅋㅋㅋㅋ
하지만 저희는 코틀린을 쓰니까 `?:`를 활용하는게 좋을거같아요! 
`.orElseThrow` 부분 모두 수정해주시면 될 것 같습니다.

2024-06-12 14:50 UTC, devitssu commented on src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/service/v1/RecipeService.kt
> +        val course = courseRepository.findById(courseId).orElseThrow { RuntimeException("Course not found") }
`RuntimeException`보다는 `ModelNotFoundException`을 사용해 주시면 좋을 것 같습니다.

2024-06-12 14:51 UTC, devitssu commented on src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/repository/v1/RecipeRepository.kt
> +    fun findByCourseAndId(course: Course, id: Long): Optional<Recipe>
아니 수정하신 커밋을 못봤네요ㅋㅋㅋㅋㅋ 바로 닫겠습니다.

2024-06-12 14:52 UTC, devitssu approved these changes

2024-06-12 16:01 UTC, 1hyung commented on src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/repository/v1/RecipeRepository.kt
> +    fun findByCourseAndId(course: Course, id: Long): Optional<Recipe>
아닙니다! 무준님이 코드 같이 봐주셔서 수정된 내용이라 알려주시면 저는 더 좋습니다! 
감사합니다!

2024-06-12 16:03 UTC, 1hyung commented on src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/service/v1/RecipeService.kt
> +            .orElseThrow { RuntimeException("Course not found") }
```
    fun getAllRecipeList(courseId: Long): List<RecipeResponse> {
        if (!courseRepository.existsById(courseId)) throw ModelNotFoundException("Course", courseId)
        return recipeRepository.findAllByCourseId(courseId).map { RecipeResponse.from(it) }
    }
```

혹시 이렇게 작성한 것은 어떨까요??

2024-06-12 16:04 UTC, 1hyung commented on src/main/kotlin/team/sparta/onehouronemeal/domain/recipe/service/v1/RecipeService.kt
> +        val course = courseRepository.findById(courseId).orElseThrow { RuntimeException("Course not found") }
```
    fun getRecipeById(courseId: Long, recipeId: Long): RecipeResponse {
        if (!courseRepository.existsById(courseId)) throw ModelNotFoundException("Course", courseId)
        val recipe =
            recipeRepository.findByCourseIdAndId(courseId, recipeId) ?: throw ModelNotFoundException("Recipe", recipeId)
        return RecipeResponse.from(recipe)
    } 
```
수정했습니다! 확인 부탁드리겠습니다!

2024-06-13 00:03 UTC, mobzzzzz approved these changes
고생하셨습니다! 👍

2024-06-13 00:07 UTC, merged