✨ 이전 패스워드에 대한 처리
one-day-one-meal/one-hour-one-meal pull request #80
Opened 2024-06-14 12:33 UTC by mobzzzzz

## 요약
> 간단 요약

이전 패스워드 3회에 대한 변경을 막습니다.
이전 패스워드 테이블에 해당 유저가 패스워드 3개를 초과하면 삭제와 생성을 함께 진행합니다.
QueryDSL을 사용했습니다

## 작업 사항

> PR에서 작업한 사항들을 적어주세요(이미지, 스크린샷등을 활용해도 좋아요)

비밀번호 수정에 password, confirmPassword 추가해서 수정 가능하게 만들기
 이전 비밀번호 검증 처리
 이전 비밀번호 3회 이상 쌓이면 제거하기

## 리뷰 요청 사항(선택)

> 리뷰시 봐주었으면 하는 부분이 있다면 적어주세요

---
### 해결한 이슈
closes: #32

2024-06-14 12:38 UTC, mobzzzzz commented
User controller Lint style이 무준님이랑 다른것같아서 저장할 때마다 자동으로 저만치 바뀌는지라 일단 그대로 올렸습니다

2024-06-14 13:36 UTC, devitssu requested changes
지금 로직은 비밀번호를 수정하지 않고 프로필을 수정하면 에러가 나는 것 같아요.
그리고 이전 비밀번호가 3개를 넘으면 3개를 모두 삭제하는게 아니라 가장 오래된 비밀번호만 삭제하면 될 것 같아요!

2024-06-15 08:27 UTC, mobzzzzz commented
@devitssu Request의 Password가 비어있을 경우에 대해 비밀번호 변경을 진행하지 않는 것으로 간주하고 수정 진행했습니다!

2024-06-15 09:16 UTC, devitssu approved these changes

2024-06-15 12:17 UTC, Moo-moo-11 approved these changes
고생하셨습니다

2024-06-16 02:00 UTC, merged